name: Mirror Repo
on: [workflow_dispatch] # Manuel tetiklemek için

jobs:
  mirror_to_github:
    runs-on: ubuntu-latest
    steps:
      - name: Mirroring
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@github.com:kullanici_adin/yeni-repon.git
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
